### ISSUE TITLE
I authorized successfully, but I am unable to redirect to my app

### ISSUE THREAD

**Issue by Appsteamvasant** [insanelydeepak/fitbit-api-example-iOS#3]
Once authorized successfully, how to get back to my app?

**Comment by insanelydeepak** [comment]
SFSafari controller is not dismissing ??

**Comment by insanelydeepak** [comment]
Hi 
It's working fine here I tested 
![simulator screen shot 15-jul-2017 10 25 01 pm](https://user-images.githubusercontent.com/9814566/28241160-c4d1676c-69ac-11e7-9fa9-f8d7fcf95ac6.png)
![simulator screen shot 15-jul-2017 10 25 29 pm](https://user-images.githubusercontent.com/9814566/28241161-c4d9a1a2-69ac-11e7-87d2-b5d36af04fd2.png)

**Comment by insanelydeepak** [comment]
> Once authorized successfully, how to get back to my app?
 you are not getting back to your app due missing URLScheme , check example info.plist , make sure your info.plist and redirectURL matches

**Comment by insanelydeepak** [comment]
I closed issue , feel free to re-open , if you still need help
