### ISSUE TITLE
 Error Message After successful Login "There was an error extracting the access token from the authentication response"

### ISSUE THREAD

**Issue by SusheelYadavAhex** [insanelydeepak/fitbit-api-example-iOS#4]
Hi Deepak, 
First of all, i would like you to thank you for Providing Wonderful SDK . So easy to use by the way. 

But actually i am facing with one issue when i am authorizing with my login details i am getting this error message ("There was an error extracting the access token from the authentication response".)

**Note**: After successful login i am able to see list of my default scope variable like (sleep+settings+nutrition+activity+social+heartrate+profile+weight+location with check boxes selected) ,but when i press "ALLOW" button i am facing with the above state issue . 

Can you please look into this and help me where i went wrong . 

Currently i am testing in Xcode version 9.2 (9C40b), i am facing same issue in Simulator and iPhone . 

Waiting for your response, 
Best Regards
Susheel Yadav

**Comment by insanelydeepak** [comment]
Hi 
i remember there was issue when fitbit was down for some reasons , it working fine for me till now 
im using this SDK in many projects 
if you still have issue let me know so i can fix it

**Comment by insanelydeepak** [comment]
Hi 
just try to find you issue it working fine 


![samplebit example](https://user-images.githubusercontent.com/9814566/35233066-20b194ce-ffc3-11e7-8547-e02570f79c70.gif)

let me know if you have issue still ?

thank you 
Deepak

**Comment by SusheelYadavAhex** [comment]
Thanks for your response, 

I will Check and let u know.

**Comment by insanelydeepak** [comment]
Good Luck

**Comment by insanelydeepak** [comment]
Hi 
i'm closing this issue , feel free to re-open
